const express=require('express')
const cors=require('cors')
const bodyParser=require('body-parser')
const userRoutes=require('./backend/routes/user')
const messageRoutes=require('./backend/routes/message')
const groupRoutes=require('./backend/routes/group')
const adminRoutes=require('./backend/routes/admin')
const app=express()
const sequelize=require('./backend/util/database')
const User=require('./backend/models/user')
const Message=require('./backend/models/message')
const Group=require('./backend/models/group')
const userGroup=require('./backend/models/userGroup')
app.use(cors())
app.use(bodyParser.json())
app.use(express.json())
app.use('/user',userRoutes)
app.use(groupRoutes)
app.use(messageRoutes)
app.use(adminRoutes)
// User.hasMany(Group)
// Group.belongsTo(User)
User.belongsToMany(Group,{through:userGroup})
Group.belongsToMany(User,{through:userGroup})
User.hasMany(Message)
Message.belongsTo(User)
// app.use('/',(req,res)=>{
//     console.log('working')
// })
sequelize.sync()
.then(()=>{
    console.log('database is connected')
    app.listen(3000)
}).catch(err=>console.log(err))

